import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/footer/Footer'
import Navbar from './components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen w-[1024px] lg:w-full'>
          <Navbar/>
          <div className='flex flex-col items-center'>
            <main className='flex justify-center items-center w-[1024px]'>{children}</main>
            <Footer/>
          </div >
        </div>
      </body>
    </html>
  )
}
